services:
  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: project3-db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - vector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  vector_data: